name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:

    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run -m unittest discover
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
